# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
