# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_prefriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
