# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='members',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
