# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=30)),
                ('description', models.TextField(default=b'')),
                ('createTime', models.CharField(max_length=30)),
                ('startTime', models.CharField(max_length=30)),
                ('endTime', models.CharField(max_length=30)),
                ('endDate', models.IntegerField(default=0)),
                ('endDateTime', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
                ('image', models.CharField(default=b'', max_length=200)),
                ('goods', models.IntegerField(default=0)),
                ('finished', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(related_name='user_plan_members', to='basic.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan_owner', to='basic.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('plans', models.ManyToManyField(related_name='plan_tag_plans', to='plan.Plan')),
            ],
        ),
    ]
