# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='createTime',
            field=models.IntegerField(default=0),
        ),
    ]
