# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='endDateTime',
        ),
        migrations.AlterField(
            model_name='plan',
            name='endTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='startTime',
            field=models.IntegerField(default=0),
        ),
    ]
