# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('plan', '0002_auto_20160104_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_planprogress_plan', to='plan.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_planprogress_user', to='basic.User')),
            ],
        ),
    ]
