# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('plan', '0002_auto_20151231_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='matchs',
            field=models.ManyToManyField(related_name='match_tag_matchs', to='match.Match'),
        ),
    ]
