# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20151231_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=30)),
                ('plans', models.ManyToManyField(related_name='plan_ptag_plans', to='plan.Plan')),
            ],
        ),
    ]
