# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('match', '0002_auto_20160104_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_members',
            field=models.ManyToManyField(related_name='user_match_members', to='basic.User'),
        ),
    ]
