# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_mtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='createTime',
            field=models.IntegerField(default=0),
        ),
    ]
